const data = [
    {
        title: { 
            id: "prefTitle0", 
            label: "Ingrepen & Algemeen",
            position: {x: 100, y: 100},
        },
        options: [
            { 
                id: "prefOxytocine", 
                label: "geen weeënopwekkers", 
                image: "images/geen-weeenopwekkers.png", 
                alt: "geen-weeenopwekkers",
                position: {x: 0, y: 100},
                hidden: false,
            },
            { 
                id: "prefVliezen", 
                label: "geen vliezen breken", 
                image: "images/geen-vliezen-breken.png", 
                alt: "geen-vliezen-breken",
                position: {x: 100, y: 100},
                hidden: false,
            },
            { 
                id: "prefEpidurale", 
                label: "geen epidurale", 
                image: "images/geen-epidurale.png", 
                alt: "geen-epidurale",
                position: {x: 200, y: 100},
                hidden: false,
            },
            { 
                id: "prefKnip", 
                label: "geen episiotomie", 
                image: "images/geen-episiotomie.png", 
                alt: "geen-episiotomie",
                position: {x: 300, y: 100},
                hidden: false,
            },
            { 
                id: "prefOverleg", 
                label: "steeds overleg en info", 
                image: "images/steeds-overleg-en-verduidelijken.png", 
                alt: "steeds-overleg-en-verduidelijken",
                position: {x: 400, y: 100},
                hidden: false,
            },
            { 
                id: "prefCare", 
                label: "handle with care", 
                image: "images/handle-with-care.png", 
                alt: "handle-with-care",
                position: {x: 475, y: 100},
                hidden: false,
            },
            { 
                id: "prefBadbevalling", 
                label: "badbevalling", 
                image: "images/badbevalling.png", 
                alt: "badbevalling",
                position: {x: 550, y: 100},
                hidden: false,
            },
            { 
                id: "prefBekkeninstabiliteit", 
                label: "let op bekkeninstabiliteit", 
                image: "images/bekkeninstabiliteit.png", 
                alt: "bekkeninstabiliteit",
                position: {x: 625, y: 100},
                hidden: false,
            },
            { 
                id: "prefFotos", 
                label: "foto's? ja, graag", 
                image: "images/fotos.png", 
                alt: "fotos",
                position: {x: 675, y: 100},
                hidden: false,
            },
            { 
                id: "prefTolk", 
                label: "tolk nodig", 
                image: "images/tolk-nodig.png", 
                alt: "tolk-nodig",
                position: {x: 750, y: 100},
                hidden: false,
            },
        ]
    },
    {
        title: { 
            id: "prefTitle", 
            label: "Sfeer & Omgeving",
            position: {x: 100, y: 225},
        },
        options: [
            { 
                id: "prefBubbel", 
                label: "laat me in mijn bubbel", 
                image: "images/bubbel.png", 
                alt: "bubbel",
                position: {x: 0, y: 275},
                hidden: false,
            },
            { 
                id: "prefGedimdLicht", 
                label: "gedimd licht", 
                image: "images/gedimd-licht.png", 
                alt: "gedimd-licht",
                position: {x: 100, y: 275},
                hidden: false,
            },
            { 
                id: "prefEigenMuziek", 
                label: "eigen muziek", 
                image: "images/eigen-muziek.png", 
                alt: "eigen-muziek",
                position: {x: 200, y: 275},
                hidden: false,
            },
            { 
                id: "prefPersoneel", 
                label: "geen stagiaires", 
                image: "images/weinig-personeel.png", 
                alt: "weinig-personeel",
                position: {x: 0, y: 375},
                hidden: false,
            },
            { 
                id: "prefRustig", 
                label: "rustige sfeer", 
                image: "images/geen-verstoringen.png", 
                alt: "geen-verstoringen",
                position: {x: 100, y: 357},
                hidden: false,
            },
            { 
                id: "prefAroma", 
                label: "aromatherapie", 
                image: "images/aromatherapie.png", 
                alt: "aromatherapie",
                position: {x: 150, y: 357},
                hidden: false,
            },
            { 
                id: "prefTENS", 
                label: "pijn bestrijden met TENS", 
                image: "images/pijnbestrijding-TENS.png", 
                alt: "pijnbestrijding-TENS",
                position: {x: 200, y: 357},
                hidden: false,
            },
            { 
                id: "prefHypnobirthing", 
                label: "hypnobirthing", 
                image: "images/hypnobirthing.png", 
                alt: "hypnobirthing",
                position: {x: 250, y: 357},
                hidden: false,
            },
        ]
    },
    {
        title: { 
            id: "prefTitle2", 
            label: "Arbeid",
            position: {x: 500, y: 225},
        },
        options: [
            { 
                id: "prefRitme", 
                label: "geen tijdsdruk", 
                image: "images/eigen-ritme.png", 
                alt: "eigen-ritme",
                position: {x: 360, y: 275},
                hidden: false,
            },
            { 
                id: "prefBewegen", 
                label: "vrij bewegen", 
                image: "images/vrij-bewegen.png", 
                alt: "vrij-bewegen",
                position: {x: 445, y: 275},
                hidden: false,
            },
            { 
                id: "prefMonitoring", 
                label: "zo min mgl aan monitor", 
                image: "images/minimale-monitoring.png", 
                alt: "minimale-monitoring",
                position: {x: 550, y: 275},
                hidden: false,
            },
            { 
                id: "prefVaginaal", 
                label: "vaginaal onderzoek beperken", 
                image: "images/vaginaal-onderzoek-beperken.png", 
                alt: "vaginaal-onderzoek-beperken",
                position: {x: 360, y: 357},
                hidden: false,
            },
            { 
                id: "prefEtenDrinken", 
                label: "eten en drinken", 
                image: "images/eten-drinken.png", 
                alt: "eten-drinken",
                position: {x: 425, y: 357},
                hidden: false,
            },
            { 
                id: "prefDouchen", 
                label: "douchen of bad mogelijk", 
                image: "images/douchen-bad-mogelijk.png", 
                alt: "douchen-bad-mogelijk",
                position: {x: 475, y: 357},
                hidden: false,
            },
            { 
                id: "prefHandsOff", 
                label: "hands-off bevalling", 
                image: "images/hands-off.png", 
                alt: "hands-off",
                position: {x: 550, y: 357},
                hidden: false,
            },
        ]
    },
    {
        title: { 
            id: "prefTitle3", 
            label: "Geboorte",
            position: {x: 750, y: 225}
        },
        options: [
            { 
                id: "prefPositie", 
                label: "verticale bevalpositie", 
                image: "images/vertikale-positie.png", 
                alt: "verticale-bevalpositie",
                position: {x: 640, y: 275},
                hidden: false,
            },
            { 
                id: "prefBaarkruk", 
                label: "baarkruk", 
                image: "images/baarkruk.png", 
                alt: "baarkruk",
                position: {x: 675, y: 275},
                hidden: false,
            },
            { 
                id: "prefPersen", 
                label: "persen op eigen ritme", 
                image: "images/persen-eigen-ritme.png", 
                alt: "persen-eigen-ritme",
                position: {x: 750, y: 275},
                hidden: false,
            },
            { 
                id: "prefBabyAanpakken", 
                label: "baby zelf aanpakken", 
                image: "images/baby-zelf-aanpakken.png", 
                alt: "baby-zelf-aanpakken",
                position: {x: 640, y: 357},
                hidden: false,
            },
            { 
                id: "prefGeboortePlacenta", 
                label: "tijd voor placenta", 
                image: "images/tijd-voor-placenta.png", 
                alt: "tijd-voor-placenta",
                position: {x: 725, y: 357},
                hidden: false,
            },
        ]
    },
    {
        title: { 
            id: "prefTitle4", 
            label: "Na de Geboorte",
            position: {x: 225, y: 450}
        },
        options: [
            { 
                id: "prefUitkloppen", 
                label: "uitkloppen navelstreng", 
                image: "images/navelstreng-laten-uitkloppen.png", 
                alt: "navelstreng-laten-uitkloppen",
                position: {x: 40, y: 500},
                hidden: false,
            },
            { 
                id: "prefCordring", 
                label: "cordring", 
                image: "images/cordring.png", 
                alt: "cordring",
                position: {x: 120, y: 500},
                hidden: false,
            },
            { 
                id: "prefPlacentaBewaren", 
                label: "placenta bewaren", 
                image: "images/placenta-bewaren.png", 
                alt: "placenta-bewaren",
                position: {x: 200, y: 500},
                hidden: false,
            },
            { 
                id: "prefFlesvoeding", 
                label: "geen flesvoeding", 
                image: "images/geen-flesvoeding.png", 
                alt: "geen-flesvoeding",
                position: {x: 250, y: 500},
                hidden: false,
            },
            { 
                id: "prefFopspeen", 
                label: "geen fopspeen", 
                image: "images/geen-fopspeen.png", 
                alt: "geen-fopspeen",
                position: {x: 300, y: 500},
                hidden: false,
            },
            { 
                id: "prefWassen", 
                label: "baby niet wassen", 
                image: "images/baby-niet-wassen.png", 
                alt: "baby-niet-wassen",
                position: {x: 350, y: 500},
                hidden: false,
            },
            { 
                id: "prefHuidOpHuid", 
                label: "tijd voor huid-op-huid", 
                image: "images/huid-op-huid.png", 
                alt: "huid-op-huid",
                position: {x: 0, y: 600},
                hidden: false,
            },
            { 
                id: "prefMutsje", 
                label: "geen mutsje", 
                image: "images/geen-mutsje.png", 
                alt: "geen-mutsje",
                position: {x: 75, y: 600},
                hidden: false,
            },
            { 
                id: "prefVitK", 
                label: "geen vitamine K", 
                image: "images/geen-vit-K.png", 
                alt: "geen-vit-K",
                position: {x: 125, y: 600},
                hidden: false,
            },
            { 
                id: "prefECG", 
                label: "ECG op de rug", 
                image: "images/ECG-op-rug.png", 
                alt: "ECG-op-rug.png",
                position: {x: 200, y: 600},
                hidden: false,
            },
            { 
                id: "prefLotus", 
                label: "lotusgeboorte", 
                image: "images/lotus.png", 
                alt: "lotus.png",
                position: {x: 275, y: 600},
                hidden: false,
            },
        ]
    },
    {
        title: { 
            id: "prefTitle5", 
            label: "Plan B / Keizersnede",
            position: {x: 600, y: 450}
        },
        options: [
            { 
                id: "prefGentleSectio", 
                label: "gentle sectio", 
                image: "images/gentle-sectio.png", 
                alt: "gentle-sectio",
                position: {x: 500, y: 500},
                hidden: false,
            },
            { 
                id: "prefDoulaBijMij", 
                label: "vroedvrouw / doula bij mij", 
                image: "images/keizersnede.png", 
                alt: "keizersnede",
                position: {x: 600, y: 500},
                hidden: false,
            },
            { 
                id: "prefBabyPartner", 
                label: "baby bij partner", 
                image: "images/baby-partner.png", 
                alt: "baby-partner",
                position: {x: 700, y: 500},
                hidden: false,
            },
        ]
    },
];

export default data;

